[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

# 缓存设置
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 重定向设置
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404